version: "3.9"  # Or a more recent version

services:
  redis:
    image: redis:7.4-alpine # Using alpine image for smaller size, use 7.2.4 or latest 7.2.x if 7.4 is unavailable as alpine images often lag slightly
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Named volume for persistence
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5' # Limit CPU usage
          memory: 512M # Limit memory usage for container, not redis itself.
    security_opt:
      - no-new-privileges:true
    ulimits:
      memlock: -1
      nofile: 65536
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN

volumes:
  redis_data:
