#Tue Jan 21 07:27:32 PST 2025
micronaut:
  metrics:
    enabled: true
    export:
      jmx:
        enabled: true
        step: PT1M
  application:
    name: cosmic-sentry
  http:
    services:
      neows: # NASA Near Earth Object Web Service (NEOWS)
        url: "https://api.nasa.gov"
graphql:
  enabled: true
  path: /graphql
  graphiql: # enables the /graphiql endpoint to test calls against your graph.
    enabled: true
redis:
  uri: "redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@localhost:6379"
nasa:
  api:
    key: "${NASA_API_KEY}"
    neows:
      url-path: "/neo/rest/v1/feed"
