# redis.conf

# To see AUTH events
loglevel debug

# Default user password for authentication
requirepass ketchup1234

#user default on nopass # Disable default user with no password

# Create a specific user with a password and permissions
user redisuser on +@all allchannels >mayonnaise9865

# Enable append-only mode for data persistence
appendonly yes

# Set maximum memory usage
maxmemory 256mb

# Set memory eviction policy
maxmemory-policy allkeys-lru

#aclfile /etc/redis/users.acl